### ISSUE TITLE
Accept commit messages generated by GitHub's Squash & Merge feature

### ISSUE THREAD

**Issue by krahlro-sick** [mristin/opinionated-commit-message#29] opened 2020-07-08 09:52 UTC
[This commit](https://github.com/admin-shell-io/aasx-package-explorer/commit/dabb94ddec11272a3568c1e908e69dea4236c0bd) was generated using GitHub's Squash & Merge feature.  The check [failed](https://github.com/admin-shell-io/aasx-package-explorer/runs/822822795#step:3:3) because of the asterisk in the first line of the body.  But in my opinion, the commit message checker should've accepted the commit as it was based on commits with valid messages.

**Comment by mristin** [comment] 2020-07-09 08:06
This is by design. This form prevents people from submitting messages with uninformative bodies. A short introductory sentence usually suffices to force the developer to look at the commit message again and succinctly formulate what the pull request is effecting (*e.g.*, change, add, fix *etc.*).

**Comment by mristin** [comment] 2020-07-09 13:58
Sorry for closing the issue; this needs more thought. Actually, the developer will most probably not change the message only to see the check fail on master.

**Comment by mristin** [comment] 2020-07-09 19:27
Pardon, wrong issue -- pull request #38 does NOT fixes this issue.

**Comment by mristin** [comment] 2020-07-09 19:52
Fixed by #39 .

**Closed by mristin** 2020-07-09 19:52 UTC
